### ISSUE TITLE
Missing sides

### ISSUE THREAD

**Issue by spakin** [samcarter/TikZbricks#1]
I just tried out TikZbricks, and it looks like it's drawing only the the three sides of each brick that are visible with the default viewport.  Different viewports expose the missing sides:
```LaTeX
\begin{wall}[scale=0.5]
  \tdplotsetmaincoords{70}{45}
  \wallbrick[color=red]{4}{2}
  \newrow
  \wallbrick[color=yellow]{2}{2}
  \wallbrick[color=blue]{2}{2}
\end{wall}
```
![partial-bricks](https://user-images.githubusercontent.com/650041/129605888-bc1eb20e-a598-4d8c-96d2-06e8e77ac3e5.png)

**Comment by samcarter** [comment]
Thanks for the report! I made some adjustments to fix this bug for rotating in the xy plane.

![test](https://user-images.githubusercontent.com/43832342/129634708-a164096e-a7b6-4e13-8a5e-1904408f7574.png)

![document](https://user-images.githubusercontent.com/43832342/129638941-77fb1260-4bc2-4908-84c0-1fa70e23848c.gif)


I'll see if I can also come up with something for the yz plane...

**Comment by spakin** [comment]
Thanks for addressing this so promptly.  As another test case, here's a rotation of -45°:
```LaTeX
\begin{wall}[scale=0.5]
  \tdplotsetmaincoords{70}{-45}
  \wallbrick[color=red]{4}{2}
  \newrow
  \wallbrick[color=yellow]{2}{2}
  \wallbrick[color=blue]{2}{2}
\end{wall}
```
![partial-bricks-2](https://user-images.githubusercontent.com/650041/129635973-b306478b-3c8f-4336-a79f-d1644cce6cd5.png)

**Comment by samcarter** [comment]
yes, that's a consequence of the limitation that walls have to be build from right to left. You can works around the problem like this:

```
\documentclass{standalone}

\usepackage{tikzbricks}

\begin{document}
\begin{wall}[scale=0.5]
  \tdplotsetmaincoords{70}{-45}
  \wallbrick[color=red]{4}{2}
  \newrow
  \addtocounter{brickx}{2}
  \wallbrick[color=blue]{2}{2}
  \addtocounter{brickx}{-4}
  \wallbrick[color=yellow]{2}{2}
\end{wall}

\end{document}
```

![document2](https://user-images.githubusercontent.com/43832342/129636510-a414522c-17a7-4554-937c-f35eea794aae.png)

**Comment by spakin** [comment]
Got it; thanks.  Out of curiosity, why did you decide to draw walls right-to-left instead of left-to-right?

**Comment by samcarter** [comment]
Oh, that's easy to answer: with the default viewpoint I'm using, left-to-right would result in a problem like https://user-images.githubusercontent.com/650041/129635973-b306478b-3c8f-4336-a79f-d1644cce6cd5.png so I used the other direction :)

**Comment by spakin** [comment]
😄
