### ISSUE TITLE
Add text to the bricks

### ISSUE THREAD

**Issue by thomas-saigre** [samcarter/TikZbricks#5]
Hi!

I'm not sure this is exactly an issue with the library, but I put this here ;)

I managed to add a feature allowing the display of text on the face of the brick.
This is not perfect because if the text is too long, then it extends beyond the brick, but for the usage I'm planning to do, it will be fine enough.

Also, we cannot set the face where the text appears:

![image](https://github.com/user-attachments/assets/df51ff17-05fc-46b2-8d55-1e9720e6808c)

Is this feature worse I make a PR for this contribution?

**Comment by samcarter** [comment]
Thanks for the suggestion! 

I think this might be a useful thing to have. I've seen people using building blocks with text on them in many different ways, for example in presentations when showing components of something or different steps ...

If it isn't too much trouble, I'd love to see your code for this!

**Comment by thomas-saigre** [comment]
Solved in #6
